version: "3.8"

services:
  api1: # API - Instância 01
    image: pr3d4dor/rinha-de-backend-2023-q3-php-puro:latest
    hostname: api1
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: rinha
      DB_USER: root
      DB_PASSWORD: rinha
      REDIS_HOST: cache
      REDIS_PORT: 6379
    depends_on:
      - db
      - cache
    expose:
      - "80"
    deploy:
      resources:
        limits:
          cpus: '0.05'
          memory: '0.25GB'
    networks:
      - rinha-php-puro

  api2: # API - Instância 02
    image: pr3d4dor/rinha-de-backend-2023-q3-php-puro:latest
    hostname: api2
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: rinha
      DB_USER: root
      DB_PASSWORD: rinha
      REDIS_HOST: cache
      REDIS_PORT: 6379
    depends_on:
      - db
      - cache
    expose:
      - "80"
    deploy:
      resources:
        limits:
          cpus: '0.05'
          memory: '0.25GB'
    networks:
      - rinha-php-puro

  nginx: # Load Balancer
    image: nginx:1.25-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.05'
          memory: '0.1GB'
    networks:
      - rinha-php-puro

  db: # Banco de dados
    image: postgres:15.4-alpine
    hostname: db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rinha
      POSTGRES_DB: rinha
    command: postgres -c shared_buffers=256MB
    volumes:
      - ./migrations.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    deploy:
      resources:
        limits:
          cpus: '1.3'
          memory: '2.3GB'
    networks:
      - rinha-php-puro

  cache: # Cache
    image: redis:7.2-alpine
    deploy:
      resources:
        limits:
          cpus: "0.05"
          memory: "0.1GB"
    networks:
      - rinha-php-puro

networks:
  rinha-php-puro:
    name: rinha-php-puro
