version: '3.5'
services:
  database:
    image: postgres:latest
    command: postgres -c 'max_connections=410'
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=rinha_backend
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '0.8'
          memory: '2.1GB'

  api1:
    image: oliveigah/rinha-backend:finalv2
    depends_on:
      - database
    hostname: api1.com
    environment:
      HTTP_SERVER_PORT: 3000
      RELEASE_COOKIE: "secret_cookie"
      RELEASE_NODE: "api@api1.com"
      RELEASE_DISTRIBUTION: "name"
      BOOTSTRAP_NODES: "api@api2.com"
      DB_CONNS: 200
    healthcheck:
      test: curl -f http://api1:3000
    deploy:
      resources:
        limits:
          cpus: '0.275'
          memory: '0.4GB'

  api2:
    image: oliveigah/rinha-backend:finalv2
    depends_on:
      - api1
    hostname: api2.com
    environment:
      HTTP_SERVER_PORT: 3000
      RELEASE_COOKIE: "secret_cookie"
      RELEASE_NODE: "api@api2.com"
      RELEASE_DISTRIBUTION: "name"
      BOOTSTRAP_NODES: "api@api1.com"
      DB_CONNS: 200
    healthcheck:
      test: curl -f http://api2:3000
    deploy:
      resources:
        limits:
          cpus: '0.275'
          memory: '0.4GB'

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '0.1GB'

volumes:
  database: