version: '3.5'
services:
  api1:
    image: thalesmaciel/rode
    hostname: api1
    depends_on:
      db:
        condition: service_healthy
    expose:
      - "80"
    environment:
      DB_HOST: db
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.6GB'

  api2:
    image: thalesmaciel/rode
    hostname: api2
    depends_on:
      db:
        condition: service_healthy
    expose:
      - "80"
    environment:
      DB_HOST: db
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.6GB'

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.20'
          memory: '0.3GB'

  db:
    image: postgres:15
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
    deploy:
      resources:
        limits:
          cpus: '0.80'
          memory: '1.5GB'
