version: '3.9'
name: 'rinha-brunoborges'

services:
  api1:
    image: brunoborges/rinha-brborges-api:arm64
    platform: linux/arm64
    hostname: api1
    environment:
      - SERVER_PORT=8080
      - DATABASE_URL=jdbc:postgresql://db-postgresql:5432/rinhadb
      - DATABASE_USERNAME=rinha
      - DATABASE_PASSWORD=rinha123
    depends_on:
      db-postgresql:
        condition: service_healthy
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: '960MB'
    networks:
      - app-network
    healthcheck:
      test: curl -o /dev/null -s --retry 0 --head http://localhost:8080/contagem-pessoas || exit 1
      interval: 10s
      retries: 5
      start_period: 20s
      timeout: 5s

  api2:
    image: brunoborges/rinha-brborges-api:arm64
    platform: linux/arm64
    hostname: api2
    environment:
      - SERVER_PORT=8080
      - DATABASE_URL=jdbc:postgresql://db-postgresql:5432/rinhadb
      - DATABASE_USERNAME=rinha
      - DATABASE_PASSWORD=rinha123
    volumes:
      - ./ddl.sql:/docker-entrypoint-initdb.d/ddl.sql
    depends_on:
      db-postgresql:
        condition: service_healthy
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: '960MB'
    networks:
        - app-network
    healthcheck:
      test: curl -o /dev/null -s --retry 0 --head http://localhost:8080/contagem-pessoas || exit 1
      interval: 10s
      retries: 5
      start_period: 20s
      timeout: 5s

  nginx:
    image: nginx:latest
    platform: linux/arm64
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      api1:
        condition: service_healthy
      api2:
        condition: service_healthy
    ports:
      - "9999:9999"
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '128MB'

  db-postgresql:
    image: postgres:latest
    platform: linux/arm64
    command: 'postgres -c max_connections=200 -c shared_buffers=256MB -c synchronous_commit=off -c fsync=off -c full_page_writes=off'
    hostname: db-postgresql
    environment:
      - POSTGRES_PASSWORD=rinha123
      - POSTGRES_USER=rinha
      - POSTGRES_DB=rinhadb
    ports:
      - "5432:5432"
    volumes:
      - ./ddl.sql:/docker-entrypoint-initdb.d/ddl.sql
    deploy:
      resources:
        limits:
          cpus: '0.8'
          memory: '1GB'
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s

networks:
  app-network:
