name: Contador

permissions:
  contents: write

on:
  push:
    branches: [ 'main' ]
    paths: [ './participantes/*/docker-compose.yml' ]

env:
  NODE_VERSION: 20.5.1

jobs:
  atualiza-contador:
    name: Atualizar o contador de participantes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout da branch
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Configura o node v${{ env.NODE_VERSION }}
        uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3.8.1
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: './apps/contador-de-participantes/package-lock.json'

      - name: Atualiza o SVG do contador
        run: node index.js ../../participantes/ ../../misc/contador-de-participantes.svg
        working-directory: './apps/contador-de-participantes'

      - name: Comita o SVG atualizado
        uses: stefanzweifel/git-auto-commit-action@3ea6ae190baf489ba007f7c92608f33ce20ef04a # v4.16.0
        with:
          commit_message: 'Contador de participantes atualizado'
          file_pattern: 'contador-de-participantes/dist/number.svg'
